// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECY2-ibHQpBnDSTZ62nggyQp9CBL80h0',
    appId: '1:565935943941:web:bac0348dfe28222581c76c',
    messagingSenderId: '565935943941',
    projectId: 'keepnote-1e860',
    authDomain: 'keepnote-1e860.firebaseapp.com',
    storageBucket: 'keepnote-1e860.appspot.com',
    measurementId: 'G-0E6Z4WC4BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR23UMGOJBDi3ZYszj5yez4_9_efZdQ08',
    appId: '1:565935943941:android:5eb310309842f4ed81c76c',
    messagingSenderId: '565935943941',
    projectId: 'keepnote-1e860',
    storageBucket: 'keepnote-1e860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA14D6Fwv-tBcPrkEvm509gIEq7kFYYgHY',
    appId: '1:565935943941:ios:f01fee6058f2729b81c76c',
    messagingSenderId: '565935943941',
    projectId: 'keepnote-1e860',
    storageBucket: 'keepnote-1e860.appspot.com',
    iosBundleId: 'com.example.keepNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA14D6Fwv-tBcPrkEvm509gIEq7kFYYgHY',
    appId: '1:565935943941:ios:f01fee6058f2729b81c76c',
    messagingSenderId: '565935943941',
    projectId: 'keepnote-1e860',
    storageBucket: 'keepnote-1e860.appspot.com',
    iosBundleId: 'com.example.keepNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBECY2-ibHQpBnDSTZ62nggyQp9CBL80h0',
    appId: '1:565935943941:web:e83d03f3846afcfd81c76c',
    messagingSenderId: '565935943941',
    projectId: 'keepnote-1e860',
    authDomain: 'keepnote-1e860.firebaseapp.com',
    storageBucket: 'keepnote-1e860.appspot.com',
    measurementId: 'G-BNLXELW3BN',
  );
}
